services:
  db: 
    image: postgres:15
    container_name: library_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    networks:
      - app_network

  test_db: 
    image: postgres:15
    container_name: test_library_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_library
    ports:
      - 5433:5432
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: library_redis
    ports:
      - 6379:6379
    networks:
      - app_network

  app:
    build:
      context: .
    container_name: app_backend
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["./docker/app.sh"]
    ports:
      - 8000:8000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge