"""edit book_issuance

Revision ID: 4b04e8cae827
Revises: e625b16e7c7e
Create Date: 2025-01-21 00:04:39.386297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b04e8cae827'
down_revision: Union[str, None] = 'e625b16e7c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_issuance', sa.Column('is_return', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_issuance', 'is_return')
    # ### end Alembic commands ###
